In [1]:
import numpy as np 
import time

In [2]:
npArr = np.random.rand(5)
print(npArr)

[0.26431569 0.75201282 0.10213298 0.29365491 0.41517481]


In [3]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
print('a= ', a)
print('b =',b)

a=  [0.69544853 0.6697988  0.56461727 ... 0.00714095 0.64688066 0.50971555]
b = [0.2346999  0.53194852 0.19813578 ... 0.62701078 0.74694773 0.7418544 ]


In [5]:
c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("non-vectorized version: " + str(1000 * (toc-tic)) + " ms")

250314.4459857101
non-vectorized version: 465.93666076660156 ms


In [6]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("vectorized version: " + str(1000 * (toc-tic)) + " ms")


250314.44598571016
vectorized version: 4.362344741821289 ms


In [7]:
import numpy as np 
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
cal  = A.sum(axis = 0)

percentage = 100 * A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [ ]:
# python enlraging 
m1 = np.array([[1,2,3],
               [4,5,6]])
m2 = np.array([100, 200, 300])

#in algbera math should be not able to suming m1 and m2 but python do enlraging 
m3 =m1 +m2
print(m3)

# bad issues realted to the Broadcasting in Python in
import numpy as np
a = np.random.randn(5) 
print(a)
#[5.6 ,4.5 ,3.4 ,2.3 ,1.2] 
print(a.shape)
print(a.T)
#] 5.6 ,4.5 ,3.4 ,2.3 ,1.2 [ #
print(np.dot(a,a.T))
#4.06


[[101 202 303]
 [104 205 306]]
[ 0.53188082 -0.16290139 -1.81928559  0.00211717  0.40484303]
(5,)
[ 0.53188082 -0.16290139 -1.81928559  0.00211717  0.40484303]
3.7831364996515906
